# Import Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load te data

In [ ]:
dataset = pd.read_csv(r"/content/twitter_training.csv",header= None)

In [ ]:
dataset

0            1         2  \
0       2401  Borderlands  Positive   
1       2401  Borderlands  Positive   
2       2401  Borderlands  Positive   
3       2401  Borderlands  Positive   
4       2401  Borderlands  Positive   
...      ...          ...       ...   
46290  11944      Verizon   Neutral   
46291  11944      Verizon   Neutral   
46292  11944      Verizon   Neutral   
46293  11944      Verizon   Neutral   
46294  11944      Verizon   Neutral   

                                                       3  
0      im getting on borderlands and i will murder yo...  
1      I am coming to the borders and I will kill you...  
2      im getting on borderlands and i will kill you ...  
3      im coming on borderlands and i will murder you...  
4      im getting on borderlands 2 and i will murder ...  
...                                                  ...  
46290  The last 3 August’s I have broken my phone. Th...  
46291  The last 3 August's I've broken my phone. This...  
46292  The last time I broke my phone was on August 3...  
46293  The last 3 August’s I have broken my phone. Th...  
46294                                                 7   

[46295 rows x 4 columns]

In [ ]:
dataset[2].unique()

array(['Positive', 'Neutral', 'Negative', 'Irrelevant'], dtype=object)

In [ ]:
dataset[2].value_counts()

2
Positive      13710
Negative      12300
Neutral       11483
Irrelevant     8802
Name: count, dtype: int64

In [ ]:
tweets = dataset.iloc[:,3:4]

In [ ]:
tweets

3
0      im getting on borderlands and i will murder yo...
1      I am coming to the borders and I will kill you...
2      im getting on borderlands and i will kill you ...
3      im coming on borderlands and i will murder you...
4      im getting on borderlands 2 and i will murder ...
...                                                  ...
46290  The last 3 August’s I have broken my phone. Th...
46291  The last 3 August's I've broken my phone. This...
46292  The last time I broke my phone was on August 3...
46293  The last 3 August’s I have broken my phone. Th...
46294                                                 7 

[46295 rows x 1 columns]

In [ ]:
tweets.columns = ["Tweets"]

In [ ]:
tweets

Tweets
0      im getting on borderlands and i will murder yo...
1      I am coming to the borders and I will kill you...
2      im getting on borderlands and i will kill you ...
3      im coming on borderlands and i will murder you...
4      im getting on borderlands 2 and i will murder ...
...                                                  ...
46290  The last 3 August’s I have broken my phone. Th...
46291  The last 3 August's I've broken my phone. This...
46292  The last time I broke my phone was on August 3...
46293  The last 3 August’s I have broken my phone. Th...
46294                                                 7 

[46295 rows x 1 columns]

# Data Preprocessing


#### Text Cleaning:Text Cleaning: Removing special characters, numbers, and punctuation.


In [ ]:
import re

In [ ]:
re_special_char = r"[^a-z\s?!.,]"

In [ ]:
def text_preprocessing(text):
  text = str(text)
  text = text.lower()
  text = re.sub(re_special_char, "", text)
  return text

In [ ]:
tweets["Tweets"] = tweets["Tweets"].apply(text_preprocessing)

**Tokenization:** Splitting text into words or subwords.


In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tk = Tokenizer()

In [ ]:
tk.fit_on_texts(tweets["Tweets"])

In [ ]:
tk.index_word

{1: 'the',
 2: 'i',
 3: 'to',
 4: 'and',
 5: 'a',
 6: 'of',
 7: 'is',
 8: 'for',
 9: 'in',
 10: 'this',
 11: 'it',
 12: 'my',
 13: 'you',
 14: 'on',
 15: 'that',
 16: 'with',
 17: 'so',
 18: 'game',
 19: 'just',
 20: 'me',
 21: 'but',
 22: 'be',
 23: 'have',
 24: 'not',
 25: 'are',
 26: 'all',
 27: 'its',
 28: 'at',
 29: 'was',
 30: 'like',
 31: 'im',
 32: 'com',
 33: 'out',
 34: 'your',
 35: 'from',
 36: 'pic',
 37: 'we',
 38: 'now',
 39: 'twitter',
 40: 'get',
 41: 'if',
 42: 'as',
 43: 'play',
 44: 'good',
 45: 'one',
 46: 'has',
 47: 'do',
 48: 'love',
 49: 'they',
 50: 'amazon',
 51: 'new',
 52: 'can',
 53: 'really',
 54: 'about',
 55: 'will',
 56: 'see',
 57: 'up',
 58: 'an',
 59: 'google',
 60: 'when',
 61: 'more',
 62: 'by',
 63: 'what',
 64: 'no',
 65: 'microsoft',
 66: 'time',
 67: 'some',
 68: 'dont',
 69: 'best',
 70: 'xbox',
 71: 'how',
 72: 'or',
 73: 'people',
 74: 'verizon',
 75: 'shit',
 76: 'why',
 77: 'cant',
 78: 'ps',
 79: 'borderlands',
 80: 'pubg',
 81: 'still',


In [ ]:
tk.index_word[20]

'me'

In [ ]:
tk.index_word[100]

'csgo'

In [ ]:
len(tk.index_word)

26086

In [ ]:
tk.word_index

{'the': 1,
 'i': 2,
 'to': 3,
 'and': 4,
 'a': 5,
 'of': 6,
 'is': 7,
 'for': 8,
 'in': 9,
 'this': 10,
 'it': 11,
 'my': 12,
 'you': 13,
 'on': 14,
 'that': 15,
 'with': 16,
 'so': 17,
 'game': 18,
 'just': 19,
 'me': 20,
 'but': 21,
 'be': 22,
 'have': 23,
 'not': 24,
 'are': 25,
 'all': 26,
 'its': 27,
 'at': 28,
 'was': 29,
 'like': 30,
 'im': 31,
 'com': 32,
 'out': 33,
 'your': 34,
 'from': 35,
 'pic': 36,
 'we': 37,
 'now': 38,
 'twitter': 39,
 'get': 40,
 'if': 41,
 'as': 42,
 'play': 43,
 'good': 44,
 'one': 45,
 'has': 46,
 'do': 47,
 'love': 48,
 'they': 49,
 'amazon': 50,
 'new': 51,
 'can': 52,
 'really': 53,
 'about': 54,
 'will': 55,
 'see': 56,
 'up': 57,
 'an': 58,
 'google': 59,
 'when': 60,
 'more': 61,
 'by': 62,
 'what': 63,
 'no': 64,
 'microsoft': 65,
 'time': 66,
 'some': 67,
 'dont': 68,
 'best': 69,
 'xbox': 70,
 'how': 71,
 'or': 72,
 'people': 73,
 'verizon': 74,
 'shit': 75,
 'why': 76,
 'cant': 77,
 'ps': 78,
 'borderlands': 79,
 'pubg': 80,
 'still': 81,


In [ ]:
tk.word_index["wow"]

236

In [ ]:
tk.word_index["are"]

25

In [ ]:
tk.word_index["you"]

13

In [ ]:
tk.texts_to_sequences(["how are you"])

[[71, 25, 13]]

In [ ]:
tweets["Tweets"][600]

'well this is certainly a development.'

In [ ]:
token_list = tk.texts_to_sequences([tweets["Tweets"][600]])

In [ ]:
token_list

[[166, 10, 7, 1159, 5, 2637]]

In [ ]:
min_word = 2

In [ ]:
token_list = token_list[0]

In [ ]:
input_seq = []
for i in range(1, len(token_list)-1):
    input_seq.append(token_list[0:i+min_word])

In [ ]:
input_seq

[[166, 10, 7],
 [166, 10, 7, 1159],
 [166, 10, 7, 1159, 5],
 [166, 10, 7, 1159, 5, 2637]]

In [ ]:
def generate_sequence(data):
    input_seq = []

    for each_tweet in data:
        token_list = tk.texts_to_sequences([each_tweet])
        token_list = token_list[0]
        for i in range(1, len(token_list)-1):
            input_seq.append(token_list[0:i+min_word])
    return input_seq

In [ ]:
input_seq = generate_sequence(tweets["Tweets"])

In [ ]:
input_seq

[[31, 180, 14],
 [31, 180, 14, 79],
 [31, 180, 14, 79, 4],
 [31, 180, 14, 79, 4, 2],
 [31, 180, 14, 79, 4, 2, 55],
 [31, 180, 14, 79, 4, 2, 55, 1803],
 [31, 180, 14, 79, 4, 2, 55, 1803, 13],
 [31, 180, 14, 79, 4, 2, 55, 1803, 13, 26],
 [2, 97, 391],
 [2, 97, 391, 3],
 [2, 97, 391, 3, 1],
 [2, 97, 391, 3, 1, 4553],
 [2, 97, 391, 3, 1, 4553, 4],
 [2, 97, 391, 3, 1, 4553, 4, 2],
 [2, 97, 391, 3, 1, 4553, 4, 2, 55],
 [2, 97, 391, 3, 1, 4553, 4, 2, 55, 426],
 [2, 97, 391, 3, 1, 4553, 4, 2, 55, 426, 13],
 [2, 97, 391, 3, 1, 4553, 4, 2, 55, 426, 13, 26],
 [31, 180, 14],
 [31, 180, 14, 79],
 [31, 180, 14, 79, 4],
 [31, 180, 14, 79, 4, 2],
 [31, 180, 14, 79, 4, 2, 55],
 [31, 180, 14, 79, 4, 2, 55, 426],
 [31, 180, 14, 79, 4, 2, 55, 426, 13],
 [31, 180, 14, 79, 4, 2, 55, 426, 13, 26],
 [31, 391, 14],
 [31, 391, 14, 79],
 [31, 391, 14, 79, 4],
 [31, 391, 14, 79, 4, 2],
 [31, 391, 14, 79, 4, 2, 55],
 [31, 391, 14, 79, 4, 2, 55, 1803],
 [31, 391, 14, 79, 4, 2, 55, 1803, 13],
 [31, 391, 14, 79, 4, 2

In [ ]:
max_seq_len = max(len(seq) for seq in input_seq)

In [ ]:
max_seq_len

166

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
input_seq = pad_sequences(input_seq, maxlen = max_seq_len, padding='pre')

In [ ]:
input_seq

array([[    0,     0,     0, ...,    31,   180,    14],
       [    0,     0,     0, ...,   180,    14,    79],
       [    0,     0,     0, ...,    14,    79,     4],
       ...,
       [    0,     0,     0, ...,   748,   412,    36],
       [    0,     0,     0, ...,   412,    36,    39],
       [    0,     0,     0, ...,    36,    39, 19482]], dtype=int32)

In [ ]:
input_seq.shape

(737079, 166)

In [ ]:
X = input_seq[:,:-1]

In [ ]:
X

array([[  0,   0,   0, ...,   0,  31, 180],
       [  0,   0,   0, ...,  31, 180,  14],
       [  0,   0,   0, ..., 180,  14,  79],
       ...,
       [  0,   0,   0, ..., 781, 748, 412],
       [  0,   0,   0, ..., 748, 412,  36],
       [  0,   0,   0, ..., 412,  36,  39]], dtype=int32)

In [ ]:
y = input_seq[:,-1]

In [ ]:
y

array([   14,    79,     4, ...,    36,    39, 19482], dtype=int32)

In [ ]:
y.shape

(737079,)

In [ ]:
X.shape

(737079, 165)

In [ ]:
vocab_size = len(tk.index_word)

In [ ]:
vocab_size

26086

**Lowercasing:** Converting all text to lowercase for uniformity.


In [ ]:
texts = tweets["Tweets"].str.lower()

In [ ]:
texts = tweets["Tweets"][0].lower()
texts

'im getting on borderlands and i will murder you all ,'

**Stopword Removal (optional):** Removing frequently used words that do not add significant meaning.


In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    words = text.split()
    filtered_words = [word for word in words if word not in stop_words]
    return " ".join(filtered_words)

tweets["Tweets"] = tweets["Tweets"].apply(remove_stopwords)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


**Padding Sequences:** Ensuring uniform input size by padding shorter sequences.


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_sequences = pad_sequences(input_seq, maxlen=50, padding='post', truncating='post')

padded_sequences

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

**Word Embedding:** Converting words into numerical representations using techniques like Word2Vec, GloVe, or embedding layers in deep learning models.



In [ ]:
from tensorflow.keras.layers import Embedding
embedding_dim = 100
vocab_size = len(tk.word_index) + 1
embedding_layer = Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_seq_len-1)


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


# Model Building


**Data Splitting:** Dividing data into training and validation sets.


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

**Model Architecture:** Creating an LSTM/GRU-based sequential model with layers including:


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=100, input_length=max_seq_len-1)) # Assuming vocab_size and max_seq_len are defined
model.add(LSTM(128))
model.add(Dense(vocab_size, activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

history = model.fit(X_train, y_train, epochs=10, batch_size=64, validation_data=(X_val, y_val))

Epoch 1/10
9214/9214 ━━━━━━━━━━━━━━━━━━━━ 4531s 491ms/step - accuracy: 0.0589 - loss: 7.0960 - val_accuracy: 0.1329 - val_loss: 6.0182
Epoch 2/10
9214/9214 ━━━━━━━━━━━━━━━━━━━━ 4780s 513ms/step - accuracy: 0.1494 - loss: 5.6541 - val_accuracy: 0.1645 - val_loss: 5.4938
Epoch 3/10
9214/9214 ━━━━━━━━━━━━━━━━━━━━ 4651s 501ms/step - accuracy: 0.1985 - loss: 4.9108 - val_accuracy: 0.1962 - val_loss: 5.1412
Epoch 4/10
9214/9214 ━━━━━━━━━━━━━━━━━━━━ 4689s 509ms/step - accuracy: 0.2563 - loss: 4.3242 - val_accuracy: 0.2289 - val_loss: 4.8852
Epoch 5/10
9214/9214 ━━━━━━━━━━━━━━━━━━━━ 4731s 512ms/step - accuracy: 0.3130 - loss: 3.8762 - val_accuracy: 0.2535 - val_loss: 4.7194
Epoch 6/10
9214/9214 ━━━━━━━━━━━━━━━━━━━━ 4663s 501ms/step - accuracy: 0.3618 - loss: 3.5336 - val_accuracy: 0.2764 - val_loss: 4.6046
Epoch 7/10
9214/9214 ━━━━━━━━━━━━━━━━━━━━ 4678s 505ms/step - accuracy: 0.3991 - loss: 3.2755 - val_accuracy: 0.2916 - val_loss: 4.5289
Epoch 8/10
9214/9214 ━━━━━━━━━━━━━━━━━━━━ 4681s 503ms/s

**Embedding Layer:** Converts words to vectors.


In [ ]:
embedding_dim = 100
vocab_size = len(tk.word_index) + 1
embedding_layer = Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_seq_len-1)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
model = Sequential()
model.add(embedding_layer)
model.add(LSTM(128))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam')

embedded_sequences = embedding_layer(X)
embedded_sequences.shape

**LSTM/GRU Layer:** Captures temporal dependencies in text.


In [ ]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs=10, batch_size=64, validation_data=(X_val, y_val))


**Dense Layer:** Fully connected layer for output.


In [ ]:
output_layer = Dense(units=vocab_size, activation='softmax')
model.add(output_layer)

model.summary()

**Softmax Activation:** Predicts probabilities for the next word.


In [ ]:
output_layer = Dense(kernel_initializer = "glorot_uniform", activation = "softmax", units = vocab_size)

**Compilation & Training:** Using loss functions like categorical cross-entropy and optimizers like Adam.

In [ ]:
loss, accuracy = model.evaluate(X_val, y_val)
print(f"Validation Loss: {loss}")
print(f"Validation Accuracy: {accuracy}")

predicted_probabilities = model.predict(X_val)
predicted_indices = np.argmax(predicted_probabilities, axis=1)

def generate_text(seed_text, next_words, model, max_sequence_len):
    for _ in range(next_words):
        token_list = tk.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
        predicted = model.predict(token_list, verbose=0)
        predicted_index = np.argmax(predicted)
        output_word = ""
        for word, index in tk.word_index.items():
            if index == predicted_index:
                output_word = word
                break
        seed_text += " " + output_word
    return seed_text


seed_text = "i am very happy"
next_words = 5
generated_text = generate_text(seed_text, next_words, model, max_seq_len)
generated_text


# Model Evaluation


**Accuracy:** The proportion of correct predictions.


In [ ]:
loss, accuracy = model.evaluate(X_val, y_val)
print(f"Validation Loss: {loss}")
print(f"Validation Accuracy: {accuracy}")


**Loss Analysis:** Monitoring training and validation loss to avoid overfitting.


In [ ]:
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper right')
plt.show()

**Human Evaluation:** Checking generated text quality for fluency and coherence.

In [ ]:
num_examples = 5
for i in range(num_examples):
  seed_text = "This is a test"
  generated_text = generate_text(seed_text, next_words=10, model=model, max_sequence_len=max_seq_len)
  print(f"Example {i+1}: {generated_text}")
  print("-" * 20)